# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2ca9ac823a3fb8241bd77808326132be77af56b4a08b9fe7683b9efd769e0cd9f3b82d32657990f1c574ea7c6b357ce0c7a28bb05bb1e432766dbc22ab0b46

test:
  secret_key_base: 152dd87ba434abe6b290bc494bd11eee74acd21e5abe04c0e52b6ad825d68ec0c35f54a438979ff3833d27d92f6cb0af49778b293f54230c8632469ee7e0c530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
